#!/bin/sh
#
# date
#

case "$1" in
  start)
	echo -n "Setting date: "
        date -s $(date -r /mnt/zImage +%Y.%m.%d-%H:%M:%S 2>/dev/null) >/dev/null 2>&1
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
